// Typeface pairing from the Stitch DESIGN.md files: Space Grotesk (headings,
// numbers, labels) + Geist (body copy). Replaces the placeholder Roboto setup.
export const fontFamilies = {
  headingRegular: 'SpaceGrotesk_400Regular',
  headingMedium: 'SpaceGrotesk_500Medium',
  headingSemiBold: 'SpaceGrotesk_600SemiBold',
  headingBold: 'SpaceGrotesk_700Bold',
  bodyRegular: 'Geist_400Regular',
  bodyMedium: 'Geist_500Medium',
  bodySemiBold: 'Geist_600SemiBold',
  heading: 'SpaceGrotesk_600SemiBold',
  body: 'Geist_400Regular',
};

export const typography = {
  displayLg: {
    fontFamily: fontFamilies.headingBold,
    fontSize: 36,
    fontWeight: '700',
    lineHeight: 44,
    letterSpacing: -0.7,
  },
  headlineLg: {
    fontFamily: fontFamilies.headingSemiBold,
    fontSize: 26,
    fontWeight: '600',
    lineHeight: 34,
    letterSpacing: -0.3,
  },
  headlineLgMobile: {
    fontFamily: fontFamilies.headingSemiBold,
    fontSize: 26,
    fontWeight: '600',
    lineHeight: 34,
    letterSpacing: -0.3,
  },
  headlineMd: {
    fontFamily: fontFamilies.headingSemiBold,
    fontSize: 22,
    fontWeight: '600',
    lineHeight: 28,
    letterSpacing: -0.2,
  },
  headlineSm: {
    fontFamily: fontFamilies.headingSemiBold,
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 24,
    letterSpacing: 0,
  },
  titleMd: {
    fontFamily: fontFamilies.headingSemiBold,
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
    letterSpacing: 0,
  },
  bodyLg: {
    fontFamily: fontFamilies.bodyRegular,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    letterSpacing: -0.16,
  },
  bodyMd: {
    fontFamily: fontFamilies.bodyRegular,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: -0.07,
  },
  bodySm: {
    fontFamily: fontFamilies.bodyRegular,
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    letterSpacing: 0,
  },
  labelCaps: {
    fontFamily: fontFamilies.headingSemiBold,
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 14,
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  labelMd: {
    fontFamily: fontFamilies.headingSemiBold,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  labelSm: {
    fontFamily: fontFamilies.headingBold,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  numericHero: {
    fontFamily: fontFamilies.headingBold,
    fontSize: 34,
    fontWeight: '700',
    lineHeight: 40,
    letterSpacing: -0.85,
    fontVariant: ['tabular-nums'],
  },
  dataMetric: {
    fontFamily: fontFamilies.headingBold,
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 28,
    letterSpacing: -0.48,
    fontVariant: ['tabular-nums'],
  },
  number: {
    fontFamily: fontFamilies.headingSemiBold,
    fontVariant: ['tabular-nums'],
  },
};
